### ISSUE TITLE
"Bedwars" module does not work properly

### ISSUE THREAD

**Issue by el1anbtw** [xia-mc/Raven-XD#11]
On many servers it does not work at all, and on some servers (like blockms) it spams chat: [r] "null"

**Comment by xia-mc** [comment]
BedWars module is made for Hypixel. But I also want it to be extended to more servers!

**Comment by el1anbtw** [comment]
> BedWars module is made for Hypixel. But I also want it to be extended to more servers!

Thank a lot!

**Comment by el1anbtw** [comment]
@TejasLamba2006 please add support for more servers, for example, the server MineBlaze with Intave.

**Comment by TejasLamba2006** [comment]
@el1anbtw could you give me the screenshot of the scoreboard in a bedwars game and any text the server sends while starting the game
