### ISSUE TITLE
与Cloud client一类的mod兼容性

### ISSUE THREAD

**Issue by chenzirui001** [xia-mc/Raven-XD#35]
raven-Bs和Cloud Client或者FPSmaster这类mod装在一起时会使游戏崩溃:(

**Comment by xia-mc** [comment]
崩溃日志？

**Comment by chenzirui001** [comment]
@xia-mc 
[cloudclient+ravenbs.log](https://github.com/user-attachments/files/16117005/cloudclient%2Bravenbs.log)
[fpsmaster+ravenbs.log](https://github.com/user-attachments/files/16117006/fpsmaster%2Bravenbs.log)
ravenbs比fpsmaster先加载时游戏可以正常启动，但fpsmaster不会起效
