### ISSUE TITLE
game instantly crashes after joining a server

### ISSUE THREAD

**Issue by Nijjj** [xia-mc/Raven-XD#48]
whenever I join a server while using your fork of bs the game crashes, I was using pojav launcher because I don't have a laptop rn.
[crash-2024-07-06_21.47.05-client.txt](https://github.com/user-attachments/files/16118035/crash-2024-07-06_21.47.05-client.txt)
Here's the crash report.

**Comment by xia-mc** [comment]
try to remove keystrokes/profile/default.json
IDK why, but it works.
