### ISSUE TITLE
RodAimbot issue

### ISSUE THREAD

**Issue by el1anbtw** [xia-mc/Raven-XD#50]
Please fix this function. I also suggest adding a new function: Rod Spam, which will automatically quickly throw a rod and switch back to the sword, somewhat similar to a macro. For classic PVP.

**Comment by xia-mc** [comment]
already known, but it's not in plan for now

**Comment by TejasLamba2006** [comment]
@xia-mc was this fixed in #83 ?

**Comment by xia-mc** [comment]
yes

> @xia-mc was this fixed in #83 ?
