### ISSUE TITLE
关于ka的意见

### ISSUE THREAD

**Issue by slznr** [xia-mc/Raven-XD#512]
主包能不能加一个rotation range在range内就会瞄准，现在是attack range跟rotation range都是一个不能分开调整，希望xia更update一下:D
(这样好模拟绿玩去打legit)

**Comment by xia-mc** [comment]
swing range?不过swing range与attack range不同时用ab可能会卡刀

**Comment by slznr** [comment]
> swing range?不过swing range与attack range不同时用ab可能会卡刀

e就是swing range 距离内会同时开始挥刀和转头
现在我问下能不能加一个转头距离以分开转头和挥刀距离不能分开设置❤

**Comment by xia-mc** [comment]
已经添加到最新Dev分支
