### ISSUE TITLE
[DEV] Aim speed on scaffold does weird rotations and breaks

### ISSUE THREAD

**Issue by xanning** [xia-mc/Raven-XD#62]
video: https://cdn.discordapp.com/attachments/1257032850830524517/1260301449393340478/Jdk8u412_2024.07.09_-_21.26.01.08.mp4?ex=668ed2b0&is=668d8130&hm=a41d928fd44b4f747c43d023c1709db6afae04523c39f266150175d9bc13d2eb&

happens when you lower down the aim speed value or modify it other then 20

if sneak is enabled always happens
if not, this time if you're on kinda edge of the block it happens, player weirdly rotates around itself and does weird block placements

**Comment by xia-mc** [comment]
already fixed in latest dev version.
