### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by ISqazi** [xia-mc/Raven-XD#625]
### Pre-suggestion checklist

- [X] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [X] This feature doesn't already exist in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Changing the settings of existing features.

### Description

I want to use my overflow animations mod but the 1.8 animations are forced with the mod even when the animations module is disabled (i dont want to use it dont suggest to use it)

**Comment by ISqazi** [comment]
remove the animations module and some render and item render mixins and fixed

**Comment by xia-mc** [comment]
Now the Animations module no longer overwrites anything when it closes.
