### ISSUE TITLE
Killaura smoothing

### ISSUE THREAD

**Issue by aoehakDoc** [xia-mc/Raven-XD#626]
### Pre-suggestion checklist

- [X] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [X] This feature doesn't already exist in the latest version of Raven XD. I've made sure my installation is up to date.
- [ ] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Adding a different kind of feature.

### Description

Have smoothing on killaura like myau client (0 - 100%)
I did not look @ the code cuz i dont know anything about coding lmao

**Comment by xia-mc** [comment]
use Rotation speed silder
