### ISSUE TITLE
Better killaura rotations

### ISSUE THREAD

**Issue by aoehakDoc** [xia-mc/Raven-XD#627]
### Pre-suggestion checklist

- [X] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [X] This feature doesn't already exist in the latest version of Raven XD. I've made sure my installation is up to date.
- [ ] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Changing the settings of existing features.

### Description

I've tried every combination of rotations on raven xd, and none of them bypass vulcan
even with a 4 month old crack of myau, i only need around 25% smoothing to fully bypass vulcan, but even with no smoothing enabled, its still flagless 99% of the time
fix the rotations or add new options pls

**Comment by xia-mc** [comment]
it does. Aim Y is false flag

**Comment by aoehakDoc** [comment]
it still flags like crazy on vulcan tho
i tried every combination of all the modes

**Comment by xia-mc** [comment]
Recoded in latest dev branch.
