### ISSUE TITLE
custom capes

### ISSUE THREAD

**Issue by aoehakDoc** [xia-mc/Raven-XD#629]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

customcape module doesnt do anything
ive tried all the default cape presets and they dont do anything, and yes, i tried the "load capes" button too
please bring back the old capes in the gui settings, atleast they actually rendered
<img width="1680" alt="Screenshot 2024-07-13 at 2 51 32 PM" src="https://github.com/user-attachments/assets/c9563183-c26d-4089-8c05-ddb5f63047a6">
as you can see, custom capes is toggled but theres nothing there
for additional info, i use macos

### Repro steps

1. choose a cape option in customcape
2. toggle the module, no cape will appear

### Raven XD version

v1.10.2 - v1.14.0

**Comment by xia-mc** [comment]
You have tried removing all other mods and the bug still happens?

**Comment by xia-mc** [comment]
fixed in latest dev brench
