### ISSUE TITLE
bring back alan34 nofall

### ISSUE THREAD

**Issue by aoehakDoc** [xia-mc/Raven-XD#630]
### Pre-suggestion checklist

- [X] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [X] This feature doesn't already exist in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Other (please explain in description)

### Description

it bypassed vulcan, and none of the other nofall modes do

**Comment by xia-mc** [comment]
i will take it back in next release.
