### ISSUE TITLE
Attempting to use `modules.getSlider` on a ModeSetting will produce a ClassCastException [Scripting API]

### ISSUE THREAD

**Issue by loud2pro** [xia-mc/Raven-XD#631]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

Hello, when I try to use your Scripting API to get a Mode Setting's current value (there is no way to get a mode setting in itself, and reading https://blowsy.gitbook.io/raven/documentation/modules tells me to use modules.getSlider), it throws a ClassCastException

Here is the code I've wrote for it:

```
void onEnable() {
	try {
		client.print(String.valueOf(modules.getSlider("RotationHandler", "Move fix")));
	} catch (ClassCastException e) {
		client.print(e.getMessage());
	}
}
```

### Repro steps

1. Make a script and put the code I've wrote there
2. Try to load the script
3. You will get an error in your chat

### Raven XD version

v1.14

**Comment by xia-mc** [comment]
Sorry, I forgot to add the ```getMode()``` API for ModeSetting.
In the next version you will be able to get the values of **SliderSetting** and **ModeSetting** via ````modules.getMode()``` or ```modules.getSilder()```.

By the way, in the current version, you can do this via reflection:
```java
void onEnable() {
    try {
        Class<?> rotationHandlerClass = Class.forName("keystrokesmod.module.impl.other.RotationHandler");
        java.lang.reflect.Field moveFixField = rotationHandlerClass.getDeclaredField("moveFix");

        Class<?> moduleManagerClass = Class.forName("keystrokesmod.module.ModuleManager");
        java.lang.reflect.Field rotationHandlerField = moduleManagerClass.getDeclaredField("rotationHandler");
        Object rotationHandler = rotationHandlerField.get(null);

        moveFixField.setAccessible(true);
        double input = ((keystrokesmod.module.setting.impl.ModeSetting) moveFixField.get(rotationHandler)).getInput();

        client.print(String.valueOf(input));
    } catch (Exception e) {
        client.print(e.getMessage());
    }
}
```

**Comment by loud2pro** [comment]
Okay, I will try that. Thanks!
