### ISSUE TITLE
物品持有显示

### ISSUE THREAD

**Issue by chenzirui001** [xia-mc/Raven-XD#632]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

当我拿着一个物品时，所有人（包括npc）都会和我持有一样的物品(nametags以及手持显示一样)
![17209084768505658497030635540998](https://github.com/user-attachments/assets/adb596ea-83ba-43ef-8228-369dae81edab)

### Repro steps

1.进入一个服务器
2.找到一个玩家或npc
3.在物品和空手间切换
4.观察对象手持物变化

### Raven XD version

1.14.0

**Comment by xia-mc** [comment]
已经知道了，并在最新的开发分支中修复
