### ISSUE TITLE
Players Hold Same Item As Player

### ISSUE THREAD

**Issue by ISqazi** [xia-mc/Raven-XD#634]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [ ] I have tried removing all other mods and the bug still happens.

### Description

whatever item ur holding all the player/bots hold the same item you are holding

### Repro steps

Hold any item in multiplayer where there are other players

### Raven XD version

v1.14.0

**Comment by xia-mc** [comment]
Issues already exists: #632
