### ISSUE TITLE
Scaffold changing aim speed bugs out, STILL HAPPENS

### ISSUE THREAD

**Issue by xanning** [xia-mc/Raven-XD#644]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

changing / lowering aim speed of scaffold results in weird rotations and that leads to a ban
I tried using different things like raycast etc leads to same if i'm changing aimspeed
Doesnt happen always but happens %80 of the time
https://streamable.com/aex1g8

### Repro steps

1. Configure Scaffold with a lower aim speed then 20 (e.g 10)
2. Enable Sneak
3. bug happens.

### Raven XD version

latest release

**Comment by xia-mc** [comment]
wait for next release

**Comment by xia-mc** [comment]
Fixed in latest dev branch
