### ISSUE TITLE
Having Animations enabled does this to player hand

### ISSUE THREAD

**Issue by xanning** [xia-mc/Raven-XD#645]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

it's so annoying and i dont think it was happening before
https://streamable.com/qy3w22

### Repro steps

1. enable animations mod
2. swing your camera

### Raven XD version

latest release

**Comment by xia-mc** [comment]
Fixed in 1.17.0
