### ISSUE TITLE
move fix not working

### ISSUE THREAD

**Issue by N0TPLAYz** [xia-mc/Raven-XD#646]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

the move fix not working in raven xd 1.15

### Repro steps

1 set the movement fix on
2 it start to flag

### Raven XD version

1.15

**Comment by xia-mc** [comment]
killaura/scaffold movefix now split into their respective modules
