### ISSUE TITLE
Killaura V2 won't register wing

### ISSUE THREAD

**Issue by VeensCal** [xia-mc/Raven-XD#649]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [ ] I have tried removing all other mods and the bug still happens.

### Description

Killaura V2 don't register hits when I don't look the player

### Repro steps

1 join a server
2 toggle ka V2
3 don't work until I hit a player

Uploading Record_2024-07-16-18-10-33_bab8561a5f94f0a53956d8cbbeaad774.mp4…

### Raven XD version

1.16.0

**Comment by VeensCal** [comment]
Uploading Record_2024-07-16-18-10-33_bab8561a5f94f0a53956d8cbbeaad774.mp4…

**Comment by VeensCal** [comment]
https://github.com/user-attachments/assets/f7bc1fc3-1b5f-49de-b4d4-3d2933d182aa

**Comment by xia-mc** [comment]
Already known, this module still under devloping.
