### ISSUE TITLE
aimassist

### ISSUE THREAD

**Issue by chenzirui001** [xia-mc/Raven-XD#651]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [ ] I have tried removing all other mods and the bug still happens.

### Description

当aimassist启用时，如果目标在准星左边，那么玩家的准星就会开始原地乱晃
![Screenshot_2024-07-16-19-11-45-738_com tungsten hmclpe](https://github.com/user-attachments/assets/916e420e-9072-4604-9097-b6175ba38c08)
其他问题：有时候准星会瞄到目标的名称标签上，可能是我的鼠标漂移导致的（启用垂直瞄准）

### Repro steps

1.找到一名玩家
2.将准星移到玩家右侧
3.启用aimassist

### Raven XD version

1.16.0

**Comment by chenzirui001** [comment]
aimassist更新把smooth as possible更没了:(

**Comment by xia-mc** [comment]
在最新的dev分支修复

**Comment by xia-mc** [comment]
> aimassist更新把smooth as possible更没了:(

在最新dev分支中，smooth as possible是默认的
