### ISSUE TITLE
Blockhit module doesn't work

### ISSUE THREAD

**Issue by GamerPROPlayER5** [xia-mc/Raven-XD#655]
### Pre-reporting checklist

- [ ] I have searched existing issues and didn't find any previous reports of this bug.
- [x] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [x] I have tried removing all other mods and the bug still happens.

### Description

Whenever I enable te blockhit module, I can neither see the animation client-side or server-side. This also works with default config.

### Repro steps

Set config to default. Enable autoclicker, enable blochit.

### Raven XD version

v1.16.0

### Crash report (if applicable)

```plaintext
The game did not crash
```

**Comment by TejasLamba2006** [comment]
Can you tell me event type?

**Comment by GamerPROPlayER5** [comment]
I've tried both, they are both broken.
