### ISSUE TITLE
Bed Plate显示错误

### ISSUE THREAD

**Issue by chenzirui001** [xia-mc/Raven-XD#661]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [x] I have tried removing all other mods and the bug still happens.

### Description

如图
![2024-07-19_06 39 37](https://github.com/user-attachments/assets/e48e952e-840b-4106-82af-f029d37092d0)

### Repro steps

1.开启bedplate
2.放置床
3.随便围点方块

### Raven XD version

1.17.1

**Comment by xia-mc** [comment]
@TejasLamba2006 font⭐renderer⭐time

**Comment by TejasLamba2006** [comment]
Could I have your modlist?

**Comment by chenzirui001** [comment]
@TejasLamba2006 
![Screenshot_2024-07-19-17-28-19-388_bin mt plus-edit](https://github.com/user-attachments/assets/bdca0e57-4c80-4e7d-92a4-1d4191f299e2)

**Comment by TejasLamba2006** [comment]
Could you try this for me?
>  I have tried removing all other mods and the bug still happens.

**Comment by chenzirui001** [comment]
![2024-07-19_09 39 53](https://github.com/user-attachments/assets/9793981e-0bb5-4dcc-ab9c-8a7965f05c2b)
![2024-07-19_09 40 14](https://github.com/user-attachments/assets/5b9ece95-d204-4d9c-9a97-12e60f515416)

**Comment by TejasLamba2006** [comment]
Its probably one of your mods conflicting
