### ISSUE TITLE
BridgeAssist

### ISSUE THREAD

**Issue by chenzirui001** [xia-mc/Raven-XD#662]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [ ] I have tried removing all other mods and the bug still happens.

### Description

Bridge的AlignSpeed设置为小于100的值时,准星就会开始乱晃
![2024-07-19_07 38 17](https://github.com/user-attachments/assets/32baa765-4e4f-4270-98c5-9b88e6b3c2d1)
![1](https://github.com/user-attachments/assets/6a4e2509-1afe-4cc1-85dd-06c70fb1c8f6)

### Repro steps

1.将AlignSpeed调小,开启Work only in sneaking
2.在方块边缘按下潜行

### Raven XD version

1.17.1

**Comment by xia-mc** [comment]
@Pyggers

**Comment by Pyggers** [comment]
will look into it
