### ISSUE TITLE
当高度不在同一水平时,AimAssist瞄准出错

### ISSUE THREAD

**Issue by chenzirui001** [xia-mc/Raven-XD#663]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [ ] I have tried removing all other mods and the bug still happens.

### Description

大概会瞄准到这一位置
![2024-07-19_07 45 50](https://github.com/user-attachments/assets/9e1b1044-ace3-46d3-b874-2f1b5da78ba3)
水平7.2垂直8.4
(不清楚是不是Unisocraft反作弊检测)

### Repro steps

1.Aimassist水平和垂直速度拉大
2.与目标处于不同的Y轴高度
3.开启Aimassist,并在目标周围环绕

### Raven XD version

1.17.1

**Comment by chenzirui001** [comment]
补充:
已开Antibot

**Comment by xia-mc** [comment]
好像是boundingbox调错了，本来是想仿照vape的aimassist的（会瞄准人物上半部分）

**Comment by xia-mc** [comment]
已在最新dev分支修复
