### ISSUE TITLE
being banned from discord cuz double counter thinks im alt

### ISSUE THREAD

**Issue by D1am0nds-Ore** [xia-mc/Raven-XD#667]
### Pre-reporting checklist

- [ ] I have searched existing issues and didn't find any previous reports of this bug.
- [ ] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [ ] I have tried removing all other mods and the bug still happens.

### Description

1

### Repro steps

i just click "join discord"button and get straightly banned from double counter cuz it thinks im alt
discord:d1am0nds_ore

### Raven XD version

1

### Crash report (if applicable)

```plaintext
1
```

**Comment by D1am0nds-Ore** [comment]
i know this is nerdy but brrrr

**Comment by TejasLamba2006** [comment]
Yes you are an alt of account `1132763676135411763` (aveln.)

**Comment by D1am0nds-Ore** [comment]
wtf whos that

**Comment by D1am0nds-Ore** [comment]
i think the reason is im opening my vpn

**Comment by D1am0nds-Ore** [comment]
do  you need me to proof im not an alt

**Comment by TejasLamba2006** [comment]
> i think the reason is im opening my vpn

You have been unbanned try again by disabling your VPN
![image](https://github.com/user-attachments/assets/fa0916ba-6bad-4aa0-8087-33ed8095a020)

**Comment by D1am0nds-Ore** [comment]
alr

**Comment by D1am0nds-Ore** [comment]
nah it still thinks im an alt

**Comment by D1am0nds-Ore** [comment]
so wired

**Comment by TejasLamba2006** [comment]
You havnt verified again

> nah it still thinks im an alt

![image](https://github.com/user-attachments/assets/175d92e0-055d-4265-9f46-23e10f31d4fb)
Click

**Comment by D1am0nds-Ore** [comment]
alr
![image](https://github.com/user-attachments/assets/60269881-a586-461b-bf83-090c9611d708)

**Comment by D1am0nds-Ore** [comment]
ive trying soo hard

**Comment by Vaeyxx** [comment]
just wash your teeth
