### ISSUE TITLE
freelook make game crash

### ISSUE THREAD

**Issue by Eternal-cloud** [xia-mc/Raven-XD#671]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [ ] I have tried removing all other mods and the bug still happens.

### Description

enable freelook in cloverpixel server will make game crash.
i didn't try in another server

### Repro steps

enable freelook in cloverpixel

### Raven XD version

1.18

**Comment by xia-mc** [comment]
we need crash log
