### ISSUE TITLE
Auto click randomizer / Raven auto click add with fire button

### ISSUE THREAD

**Issue by xXGuiXxYT** [xia-mc/Raven-XD#672]
### Pre-suggestion checklist

- [ ] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [ ] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [x] This feature doesn't already exist in the latest version of Raven XD. I've made sure my installation is up to date.
- [ ] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Other (please explain in description)

### Description

Suggestion: I think it would be nice if autoclick had a randomizer or made the clicks from Raven XD autoclick (latest version) add up to the clicks from my mouse autoclick

**Comment by dylan0356** [comment]
It does randomize?

**Comment by xXGuiXxYT** [comment]
> It does randomize?

What?
