### ISSUE TITLE
add legitaura

### ISSUE THREAD

**Issue by slznr** [xia-mc/Raven-XD#677]
### Pre-suggestion checklist

- [X] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [X] This feature doesn't already exist in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Changing the settings of existing features.

### Description

（以下功能可以合并进现有的killaura模块中或另起一个模块）
一.另起一个模块
  1.只有横向瞄准没有竖向瞄准，竖向转头为当前角色在客户端层面的竖向朝向（仅在ka fov中启用）
  2.（最好添加一个weapon only这样的legit设置啥的）
二.添加在当前kilaura的中（是combat里的那个哈）
   子方案：
                （1）将ka中aim speed和aimassit一样分开设置横向竖向转头速度
                （2）令起一个设置选项来改变是否关闭竖向瞄准
（好像我的要求有点过分:(,自己有种当甲方的感觉了（x)也是希望最好能出这个吧:D)
(感谢🙏）

**Comment by xia-mc** [comment]
有点麻烦，或许可以像AutoClicker一样，把AimAssist模块拆分开来给需要瞄准的模块用。不过AimAssist的算法要比AutoClicker复杂不少，不一定能搬过去

**Comment by slznr** [comment]
补充：这个是要跟ka一样客户端视觉和服务端视觉不一样就是ka里的rotation mode选none一样的效果

**Comment by xia-mc** [comment]
> 补充：这个是要跟ka一样客户端视角和服务端视角不一样就是ka里的rotation mode选none一样的效果 （忘说了xd）

none就是无转头阿

**Comment by slznr** [comment]
> > 补充：这个是要跟ka一样客户端视角和服务端视角不一样就是ka里的rotation mode选none一样的效果 （忘说了xd）
> 
> none就是无转头阿
想说slient的sry XD

**Comment by xia-mc** [comment]
不好写gg

**Comment by slznr** [comment]
> 不好写gg
gg :O

**Comment by qloha** [comment]
ok

**Comment by qloha** [comment]
WAIT NO BUTTER???

**Comment by qloha** [comment]
ok i should stop ... bread ... its spamming discord
long live the cheeeeeeseeee
