### ISSUE TITLE
When loading a saved profile, the speed module is always set to Hypixel A

### ISSUE THREAD

**Issue by MigRget** [xia-mc/Raven-XD#678]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

so when i save a profile and load another one and load the profile agian, the module speed is always hypixel A.

### Repro steps

1.save a config
2.load another config
3.load the same config that you saved

### Raven XD version

1.19.0

**Comment by xia-mc** [comment]
yes, i will fix it later
