### ISSUE TITLE
timerrange issue

### ISSUE THREAD

**Issue by Nokity4444** [xia-mc/Raven-XD#682]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [ ] I have tried removing all other mods and the bug still happens.

### Description

timer range somehow makes everything freezing like time stop (this is so goofy)

### Repro steps

![Screenshot 2024-07-29 190117](https://github.com/user-attachments/assets/f0076094-0904-443f-984c-37deda34f1a5)

sorry for the video that too large i could't uploaded >_<

### Raven XD version

latest

**Comment by xia-mc** [comment]
Fixed in latest dev branch
