### ISSUE TITLE
R.E. Discord (f** double counter bro)

### ISSUE THREAD

**Issue by axlecoffee** [xia-mc/Raven-XD#685]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

Hihi lmfao - I was joining the ravenXD discord on my main account (was browsing yt a few days ago - joined it on my alt since thats what opens on phone due to my main acc having an outdated discord account yada yada bunch of yap) 

Basically 790736254714642453 (@axle.coffee) and my alt 967324293799219251 (@axlecoffee) both just got banned from ravenXD due to STUPID FUCKING DOUBLE COUNTER (I haven't said anything in either servers just needed to grab a config for a friend lmfao 😭) 

### Repro steps

1: Use aliucord on android (Aliucord is an old discord mod for android - its ancient and still based on the java not react version of discord and stuff like google chrome/github apps wont open discord invites to it. 
2: have the modern day discord client installed with your holding alt (just in-case my main gets termed its a kinda-backup) and have it open the link 
3: join and forget about it for like 1-4 days 
4: remember that your friend needs a client since they're on an M1 mac and basically no clients like myau support that so you go to get them a config since you're playing bw with them tonight
5: double counter touches you

### Raven XD version

nuh uh

**Comment by xia-mc** [comment]
@TejasLamba2006 Maybe we shouldn't let Double Counter be able to ban anyone.

**Comment by TejasLamba2006** [comment]
Hey @axlecoffee,

We strongly disagree with using alternate accounts on our Discord server as a measure to prevent ban evasion and raids. Your main account (ID: `790736254714642453`) has been unbanned; however, the alternate account will remain banned. We're happy to have you back!

[Join our Discord server](https://discord.gg/f92VWHgf)

**Comment by TejasLamba2006** [comment]
Keep in mind to ping me in unverified-chat and I will manually verify you, as your are flagged by double counter.
