### ISSUE TITLE
[BUG] If fly is enabled and you join a server, it keeps you stuck in the "Generating Terrain" screen

### ISSUE THREAD

**Issue by qloha** [xia-mc/Raven-XD#687]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

Basically, it just doesn't let you join if you have fly on please fix <3

### Repro steps

1. Toggle fly
2. Disconnect
3. Reconnect

### Raven XD version

1.20

### Crash report (if applicable)

```plaintext
N/A
```

**Comment by dylan0356** [comment]
Could not reproduce

**Comment by xia-mc** [comment]
Which mode of Fly?

**Comment by dylan0356** [comment]
Looks like its for Vulcan mode actually I see

**Comment by qloha** [comment]
yeah its vulcan sorry

**Comment by xia-mc** [comment]
okay, i will fix it

**Comment by dylan0356** [comment]
> okay, i will fix it

I fixed with #691
