### ISSUE TITLE
Sitting animation is broken

### ISSUE THREAD

**Issue by dophire** [xia-mc/Raven-XD#706]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

The head position of the sitting animation is broken. Looks like you're using a perspective mod. Happens even if only the client is installed with no additional mods. 

### Repro steps

Use the client. Sit on anything, stairs, entities, pigs, horses. Your character's head will be stuck in one position.
![2024-08-05_16 46 09](https://github.com/user-attachments/assets/5c4a3aeb-a40e-4afe-aef6-2c838b23467a)

### Raven XD version

1.23.1

**Comment by qloha** [comment]
looks fine ngl

**Comment by dophire** [comment]
The head is literally snapped. Its supposed to be looking at the camera, not locked in place.
![2024-08-05_16 32 10](https://github.com/user-attachments/assets/5731eb14-5b43-4ec8-85b9-b8f443846d9b)

**Comment by dophire** [comment]
Similar issue happening in the inventory. When looking down and opening the inventory, the player's head stays stuck looking down and doesn't follow the mouse cursor as it does without the client. 
![Uploading 2024-08-06_15.17.19.png…]()

**Comment by dophire** [comment]
The player head movement is completely out of sync with the camera even in F5. It takes time to catch up with the crosshair.

**Comment by TejasLamba2006** [comment]
Hi @dophire,

Could you please send me a screenshot of the rotation handler module? It would greatly help me understand the context better.

Looking forward to your response!

**Comment by dophire** [comment]
> Hi @dophire,
> 
> Could you please send me a screenshot of the rotation handler module? It would greatly help me understand the context better.
> 
> Looking forward to your response!

How can I do that?

**Comment by dophire** [comment]
> Hi @dophire,
> 
> Could you please send me a screenshot of the rotation handler module? It would greatly help me understand the context better.
> 
> Looking forward to your response!

Turning off "Rotate body" halfway fixed the issue. The body can now rotate, but the head is still stuck in one place. Current settings with fixed body rotation below. 
![image](https://github.com/user-attachments/assets/edae68c3-ea99-474f-bfa6-6857a08d04f0)
