### ISSUE TITLE
[改进]autorod

### ISSUE THREAD

**Issue by chenzirui001** [xia-mc/Raven-XD#721]
### Pre-suggestion checklist

- [X] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [ ] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [X] This feature doesn't already exist in the latest version of Raven XD. I've made sure my installation is up to date.
- [ ] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Changing the settings of existing features., Removing an old feature that doesn't work anymore.

### Description

1.主播能不能给autorod增加一个设置，在攻击之后再甩出鱼竿。
2.autorod的aim功能和rodaimbot似乎冲突了，并且autorod的瞄准会导致universocraft的回弹（可能是默认静默瞄准的原因？）
3.只要在范围内，隔着墙也会切换鱼竿
![2024-08-10_03 52 21](https://github.com/user-attachments/assets/857da075-866f-42cc-967c-c83f92eb24cd)
比如说在搭路的时候，这一举动会导致回弹

**Comment by chenzirui001** [comment]
projectileaimbot也会导致和2一样的问题

**Comment by xia-mc** [comment]
在RotationHandler里打开MoveFix: Silent

**Comment by xia-mc** [comment]
第三个问题下个版本修
