### ISSUE TITLE
This shit happens every time I join a server using V4Guard

### ISSUE THREAD

**Issue by aoehakDoc** [xia-mc/Raven-XD#722]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

<img width="1680" alt="Screenshot 2024-08-10 at 4 46 41 PM" src="https://github.com/user-attachments/assets/9dda5d66-65f0-4486-b0b4-c46d4d317706">
I even disabled all modules, so this is obviously a client issue, as it doesn't happen on other clients, like rise. 

### Repro steps

join a v4guard server
(e.g. minebox, universocraft, minelatino, etc.)

### Raven XD version

1.25

**Comment by xia-mc** [comment]
It's not Raven XD issue. There already exist ClientSpoofer and ModSpoofer module.
