### ISSUE TITLE
pls fix this buggy head movement 

### ISSUE THREAD

**Issue by N0TPLAYz** [xia-mc/Raven-XD#723]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

its push me whene i am benathe a block

### Repro steps

place a block avobe ur head

### Raven XD version

letest

**Comment by xia-mc** [comment]
I can't reproduce this.
