### ISSUE TITLE
请问你能给你的暴击模式的hitselect模块添加only in air选项吗？

### ISSUE THREAD

**Issue by baka-iqboost** [xia-mc/Raven-XD#728]
### Pre-suggestion checklist

- [X] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [X] This feature doesn't already exist in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Other (please explain in description)

### Description

Adding a new option to existed moduels.
偏好暴击时，因为在地上打不出暴击，所以应该只在空中生效才对。有时rxd在地面等暴击，敌人就会抢先摸到user，不开距离的话
优势就没了。
如图，距离明显小于三格，双方onground，而hitselect还在找暴击。
![2024-08-15_14 15 33](https://github.com/user-attachments/assets/5fb299e0-778d-4c87-b1c9-d46e4be94354)

**Comment by xia-mc** [comment]
hitselect暴击优先的工作原理：如果此时能打出暴击，跳过等待提前攻击。
对于Hypixel，更有可能的情况是延迟非常高且不稳定，导致hitselect点击选择失败。
更推荐使用较高值（60%+）的KeepSprint代替，客服看不出来。也能获得更高的命中率。

**Comment by xia-mc** [comment]
![image](https://github.com/user-attachments/assets/5613b3c0-4890-4c9e-b187-f83279f19c07)
暴击优先只会在离地时生效
