### ISSUE TITLE
StaffDetector

### ISSUE THREAD

**Issue by xXGuiXxYT** [xia-mc/Raven-XD#73]
I went to investigate the Staff detector code and realized that it only finds Staffs from servers placed in the source code. For example Hypixel. Do you think you could change this to detect employees from any server?

**Comment by xXGuiXxYT** [comment]
I think it would be better to replace the code in the StaffDetector.java file with this code: package keystrokesmod.module.impl.other;
import com.mojang.realmsclient.gui.ChatFormatting;
import keystrokesmod.Raven;
import keystrokesmod.module.Module;
import keystrokesmod.module.setting.impl.ButtonSetting;
import keystrokesmod.module.setting.impl.ModeSetting;
import keystrokesmod.utility.PacketUtils;
import keystrokesmod.utility.Utils;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.network.play.client.C01PacketChatMessage;
import java.io.*;
import java.util.*;

public class StaffDetector extends Module {

    private static final String[] INITIAL_TAGS = new String[]{"[MOD]", "[MOD+]", "[Admin]"};
    private static final Set<String> hasFlagged = new HashSet<>();

    private final ButtonSetting autoLobby = new ButtonSetting("Auto lobby", false);

    public StaffDetector() {
        super("StaffDetector", category.other);
        this.registerSetting(autoLobby);
    }

    @Override
    public void onUpdate() {
        for (EntityPlayer player : mc.theWorld.playerEntities) {
            final String name = player.getName();
            if (hasFlagged.contains(name)) continue;

            for (String tag : INITIAL_TAGS) {
                if (name.startsWith(tag)) {
                    hasFlagged.add(name);
                    Utils.sendMessage("§c§lStaff Detected: §r" + name);
                    if (autoLobby.isToggled()) {
                        PacketUtils.sendPacket(new C01PacketChatMessage("/lobby"));
                        Utils.sendMessage("Return to lobby...");
                    }
                    break;
                }
            }
        }
    }
}
Notes: I haven't tested it, so there may be bugs

**Comment by xia-mc** [comment]
99.999% Server won't show tag for staff, so it won't works.
