### ISSUE TITLE
problem about ‘esc’

### ISSUE THREAD

**Issue by pz-J** [xia-mc/Raven-XD#740]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

I can't use 'esc' to close the GUI and use the minecraft setting，just like my 'esc' was broken.

### Repro steps

1.open PCL2
2.open 1.8.9-Forge_11.15.1.2318-OptiFine_M5
3.start game
4.join in a server
5.I found I can't use my 'esc'

### Raven XD version

2.1.1

**Comment by pz-J** [comment]
I open this mod first with two other mods(the two pictures show these mods,idk were the second mod I got),when I found this question I close the first one,but my 'esc' still can't use.So I close the second mod,but the question still here.Idk why this question happened.

**Comment by xia-mc** [comment]
idk why

**Comment by baka-iqboost** [comment]
中文输入不会有冲突

**Comment by pz-J** [comment]
wc我一直以为发不了中文
我试着把所有的模组全删了，版本重新下载，都没用，还是用不了esc，可能不知道哪里和罗技的键盘产生了神秘bug。。。
