### ISSUE TITLE
add godbridge scaffold for intave and polar, like in liquidbounce

### ISSUE THREAD

**Issue by aoehakDoc** [xia-mc/Raven-XD#741]
### Pre-suggestion checklist

- [X] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [X] This feature doesn't already exist in the latest version of Raven XD. I've made sure my installation is up to date.
- [ ] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Adding a new hack., Adding a different kind of feature.

### Description

go to the edge of a block, sneak, it will automatically rotate, and when you let go it will go forward and jump every 7-8 blocks. Pls also make it work diagonal

**Comment by xia-mc** [comment]
Use static yaw and static pitch

**Comment by aoehakDoc** [comment]
no diagonal  rotations tho

**Comment by xia-mc** [comment]
ok..

**Comment by xia-mc** [comment]
not easy to do

**Comment by aoehakDoc** [comment]
cant u skid some stuff from liquidbounce (legacy)

**Comment by qloha** [comment]
its not that simple... liquidbounce is written in kotlin while raven xd is written in java.
it is possible just a bit complicated

**Comment by eonianisnoob** [comment]
> cant u skid some stuff from liquidbounce (legacy)

why dont you just use liquidbounce
