### ISSUE TITLE
关于跳跃药水的问题

### ISSUE THREAD

**Issue by baka-iqboost** [xia-mc/Raven-XD#743]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

1.使用rxd时有时喝跳跃II跳不起来，只能跳一格高。注意是有时。
2.拥有跳跃II时被几乎所有反作弊拉回，不管有没有成功jumpboost。我测试了grim, matrix, ncp, aac, vulcan, verus。watchdog未测试。只有这俩姓v的没有报vl，其它的都有拉回
<img width="397" alt="aac5" src="https://github.com/user-attachments/assets/f86af47b-a952-490c-9988-c70461ea5e1b">
<img width="396" alt="ncp" src="https://github.com/user-attachments/assets/f4142f56-8a9c-4b82-b14a-50ece4c57f9e">
<img width="396" alt="matrix" src="https://github.com/user-attachments/assets/1f8db78f-f4e1-4c5a-ac7b-6d65be208aaf">
<img width="398" alt="grim" src="https://github.com/user-attachments/assets/eb27223a-ef77-49b7-9696-c8455d72e206">

### Repro steps

1. Launch Raven XD 2.1.1
2. Join a random server
3. Join a bedwars game
4. Get 1 emerald and buy a potion of leaping
5. Get flagged by shxt anticheats

### Raven XD version

2.1.1

### Crash report (if applicable)

```plaintext
No crash so no crash reports
```

**Comment by baka-iqboost** [comment]
现在想来，一周前我就在watchdog下测试过了，直接死号了。

**Comment by baka-iqboost** [comment]
看评论看评论

**Comment by xia-mc** [comment]
这很奇怪..下个版本会修复
