### ISSUE TITLE
调整lagrange

### ISSUE THREAD

**Issue by baka-iqboost** [xia-mc/Raven-XD#746]
### Pre-suggestion checklist

- [X] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [ ] This feature doesn't already exist in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Changing the settings of existing features.

### Description

能把lagrange的delay下限调整到500ms以下吗？500ms以上有优势，但是容易被客服害死。500ms以下的看不大出来。个人认为lagrange是用来打断别人的节奏 + 让别人空刀，刚好500ms节奏感特强，打断不了别人节奏。给个合理的lagrange参数：50ms lagtime, 150ms delay, range 0-6（参考油管大神prom）。
我可以自己改，但我不想每次更新都要重新构建……所以拜托了大佬, and have a nice day.

**Comment by xia-mc** [comment]
其实可以提pull request的lol

**Comment by xia-mc** [comment]
这个更改会在下个版本加入，或者你也可以在discord下载最新dev构建
