### ISSUE TITLE
add viaversion

### ISSUE THREAD

**Issue by Daesaeho** [xia-mc/Raven-XD#749]
### Pre-suggestion checklist

- [ ] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [ ] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [ ] This feature doesn't already exist in the latest version of Raven XD. I've made sure my installation is up to date.
- [ ] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Adding a new hack.

### Description

viaversion

**Comment by nevarlackin** [comment]
![Screenshot_20240822-223417.png](https://github.com/user-attachments/assets/5ce840c3-d2f9-4df1-881d-290d3f06f69a)

Just use the mod wtf

**Comment by xia-mc** [comment]
in the plan
