### ISSUE TITLE
加入自带的跨版本

### ISSUE THREAD

**Issue by l-llllllllj** [xia-mc/Raven-XD#750]
### Pre-suggestion checklist

- [ ] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [ ] This feature doesn't already exist in the latest version of Raven XD. I've made sure my installation is up to date.
- [ ] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Adding a new hack.

### Description

如题

**Comment by FallingAngeler** [comment]
CN：
基于Raven b3的客户端有些许毛病，不支持很多模组但不限于viaversion for forge（当然Ravenb4也会很多模组不支持），如果你必须要使用viaversion进行跨版本的话，可以尝试使用viaproxy
https://github.com/ViaVersion/ViaProxy

EN（deepl）：
The Raven b3 based client has a slight bug, it doesn't support many mods but is not limited to viaversion for forge（Of course Ravenb4 will be unsupported by a lot of mods）, if you have to use viaversion for cross versioning try using viaproxy https://github.com/ViaVersion/ViaProxy
