### ISSUE TITLE
i cant sprint using raven XD

### ISSUE THREAD

**Issue by SUPERPEDRAO2312** [xia-mc/Raven-XD#753]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

when i join in any server i cant sprint, i use feather client, i can sprint without the raven XD but when i use raven glitch my game glitch

### Repro steps

1 - i open the game 
2- join in any server
3- i cant sprint in any server

### Raven XD version

2.2.1

### Crash report (if applicable)

```plaintext
none
```

**Comment by Piotrkrolik12** [comment]
Same Here, it happens from version 2.2.0 where you cant sprint

**Comment by TejasLamba2006** [comment]
Hi there,

Thank you for bringing this to our attention! Could you please let us know which launcher you are using? If you are using the **Feather** client, I want to inform you that we currently do not support it.

**Comment by TejasLamba2006** [comment]
You are using feather client most prob
