### ISSUE TITLE
当ChestStealer在盔甲栏有物品时不会工作

### ISSUE THREAD

**Issue by ItzKasumi1337** [xia-mc/Raven-XD#766]
### Pre-reporting checklist

- [ ] I have searched existing issues and didn't find any previous reports of this bug.
- [x] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [ ] I have tried removing all other mods and the bug still happens.

### Description

当ChestStealer在盔甲栏有物品时不会拿取箱子里面的盔甲换上

### Repro steps

1.打开 ChestStealer
2.打开箱子 （穿上盔甲）
3.打开另一个箱子，当箱子里面有盔甲时不会拿取

### Raven XD version

当前最新的(9.4截至)

**Comment by xia-mc** [comment]
cheststealer和invmanager的问题相当多..我会择日重写它们

**Comment by xia-mc** [comment]
临时解决方案是关闭ignore trash选项

**Comment by ItzKasumi1337** [comment]
> 临时解决方案是关闭ignore trash选项

好
