### ISSUE TITLE
i add Vietnamese 

### ISSUE THREAD

**Issue by Thanh123455678** [xia-mc/Raven-XD#767]
### Pre-suggestion checklist

- [ ] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [ ] This feature doesn't already exist in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Other (please explain in description)

### Description

I think because I'm Vietnamese, I'm very happy to be back at Raven-XD with a language for Vietnamese people.

**Comment by xia-mc** [comment]
I don't speak Vietnamese, so I can't make this translation.
