### ISSUE TITLE
打开Yeet以后崩溃客户端

### ISSUE THREAD

**Issue by ItzKasumi1337** [xia-mc/Raven-XD#771]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

如题，使用的是qq群内hypixel.json cfg

### Repro steps

123

### Raven XD version

2.4.0

**Comment by oneachina** [comment]
Yeet 本来就是崩端，逃逸用的（物理）

**Comment by ItzKasumi1337** [comment]
> Yeet 本来就是崩端，逃逸用的（物理）

无敌

**Comment by xia-mc** [comment]
bipas的建议，打开后会崩端
