### ISSUE TITLE
shop log

### ISSUE THREAD

**Issue by kittenvr** [xia-mc/Raven-XD#772]
### Pre-suggestion checklist

- [X] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [X] This feature doesn't already exist in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Adding a new hack.

### Description

something that logs when and what players buy stuff on hypixel

**Comment by xia-mc** [comment]
That's impossible

**Comment by kittenvr** [comment]
I'm pretty sure there are some scripts that do this

**Comment by xia-mc** [comment]
Minecraft server **won't** send the full inventory data, they only send helditem and armor

**Comment by kittenvr** [comment]
> I'm pretty sure there are some scripts that do this

im pretty sure this is the script hes talking about

https://github.com/Volcanware/Minecraft-Skid-Assistant/blob/main/bwt.lua

**Comment by kittenvr** [comment]
No

**Comment by kittenvr** [comment]
why are you closing this without telling me why
