### ISSUE TITLE
I Cannt Enable The "Burst Clicker" Module

### ISSUE THREAD

**Issue by maruiyuan2022** [xia-mc/Raven-XD#773]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

i cannt enable the burst clicker module in gui and bind keys
i havent enable any other modules
its the lastest version of Raven XD
is it bug or in progress?
how to solve it?
help me plz

### Repro steps

1. open raven xd by pcl2 minecraft launcher
2. create a single player world
3. press RSHIFT
4. open up the menu"combat"
5. click on the "Burst Clicker" module and it doesnt enable
6. use keybind the enable but also doesnt work

### Raven XD version

2.4.0

**Comment by casixmc** [comment]
you need to bind it
