### ISSUE TITLE
修復夏翊淳不愛郭明傑的問題

### ISSUE THREAD

**Issue by talting** [xia-mc/Raven-XD#782]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

江苏省南菁高级中学夏翊淳不喜歡青海郭明傑，請夏翊淳@xia__mc 修復這個問題。

### Repro steps

8964

### Raven XD version

8.964

### Crash report (if applicable)

```plaintext
19890604
```

**Comment by xia-mc** [comment]
魔怔
