### ISSUE TITLE
InventoryFill in AutoClicker does not work

### ISSUE THREAD

**Issue by ownerOrangutan** [xia-mc/Raven-XD#784]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

Holding down auto clicker with inventory fill mode on does not click while in guis. Cannot refill pots or sort inventories

### Repro steps

1. Enable auto clicker module
2. Enable inventory fill option
3. Does not click while in GUIs

### Raven XD version

v2.6.0

### Crash report (if applicable)

```plaintext
Did not crash
```

**Comment by xia-mc** [comment]
fixed
