### ISSUE TITLE
废物夏mc火速草我

### ISSUE THREAD

**Issue by MatrixU5er** [xia-mc/Raven-XD#786]

**Comment by xia-mc** [comment]
你说的对，但是java.lang.NullPointerException是由Sun自主研发的一款全新开放世界冒险游戏。游戏发生在一个被称作「OpenJDK」的幻想世界，在这里，被神选中的人将被授予「Object」，导引Throwable之力。你将扮演一位名为「Class<?>」的神秘角色，在自由的旅行中邂逅性格各异、能力独特的同伴们，和他们一起击败强敌，找回失散的亲人——同时，逐步发掘「java.lang.NullPointerException」的真相。

**Comment by MatrixU5er** [comment]
斐午只会关评论？

**Comment by xia-mc** [comment]
斐午只会关评论？
