### ISSUE TITLE
夏夏我真的好喜欢你啊😍做梦的时候都是梦到你的样子😍发呆的时候都是想着你的样子😍我的眼睛和心里除了夏夏谁也装不下了😍

### ISSUE THREAD

**Issue by Husky272** [xia-mc/Raven-XD#788]
### Pre-suggestion checklist

- [X] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [X] This feature doesn't already exist in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Adding a new hack.

### Description

夏夏我真的好喜欢你啊😍做梦的时候都是梦到你的样子😍发呆的时候都是想着你的样子😍我的眼睛和心里除了夏夏谁也装不下了😍

**Comment by xia-mc** [comment]
神经
