### ISSUE TITLE
投掷药水触发noslow

### ISSUE THREAD

**Issue by NikoCat233** [xia-mc/Raven-XD#789]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

丢投掷药水触发海鲜素noslow的跳跃

### Repro steps

1.开启海鲜素noslow
2.进入op duels
3.投出一瓶速度药水
4.体验bug

### Raven XD version

lastest

**Comment by NikoCat233** [comment]
另有noslow站着不动喝不了药

**Comment by NikoCat233** [comment]
另有bedbreaker死号

**Comment by Husky272** [comment]
> 另有noslow站着不动喝不了药 卡空瓶子

noslow在你没有移动的时候依然发包
