### ISSUE TITLE
the configs dont save

### ISSUE THREAD

**Issue by gio-hub-afk** [xia-mc/Raven-XD#790]
### Pre-reporting checklist

- [ ] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [ ] I have tried removing all other mods and the bug still happens.

### Description

my configs are not saving for example whenever add some thing like trigger scafold for example, if i quit and re enter the game its not riggered

### Repro steps

.

### Raven XD version

Release 2.6.0

### Crash report (if applicable)

```plaintext
there was no crash report
```

**Comment by qloha** [comment]
bruh u have to go to profiles, hover over the profile you want to save, right click, click save profile

**Comment by gio-hub-afk** [comment]
lol yeah i found that out my badd
,
