### ISSUE TITLE
Scroll bar

### ISSUE THREAD

**Issue by Zack694** [xia-mc/Raven-XD#799]
### Pre-suggestion checklist

- [ ] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [X] This feature doesn't already exist in the latest version of Raven XD. I've made sure my installation is up to date.
- [ ] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Adding a different kind of feature.

### Description

Add a scroll bar so we don't have to put the gui scale to small, PLS ADD IT ITS HARD TO CONFIG KILLAURA WHILE IN SMALL GUI SCALE CUZ ITS BLURRY

**Comment by TejasLamba2006** [comment]
Already exists

**Comment by Zack694** [comment]
No it doesn't
