### ISSUE TITLE
(Suggestion) Additional Aim Speed Randomization 

### ISSUE THREAD

**Issue by lo1am0n** [xia-mc/Raven-XD#801]
### Pre-suggestion checklist

- [X] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [X] This feature doesn't already exist in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Changing the settings of existing features.

### Description

For what I’m aware of, aim assist doesn’t have the best randomization. 

Here is what I think should be added for randomization:
- Minimum and maximum yaw speed
- Minimum and maximum pitch speed
- An option to prevent yaw and pitch speeds from being the same
- Different ways the aim assist can smooth rotations (linear smoothing for example)

I could probably open a pull request for this but I’m not at home right now.

**Comment by xia-mc** [comment]
yes, we need it

**Comment by xia-mc** [comment]
and we need the mouse sens simulator
