### ISSUE TITLE
Killaura Attacks Entities Behind Walls When Player Turns Away

### ISSUE THREAD

**Issue by celakk1** [xia-mc/Raven-XD#805]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

Basically, whenever an entity / player is behind a wall, and you turn / look away from the entity, it will start attacking it through the wall, even if option "Hit Through Blocks" is disabled.
Demonstration of the bug:
https://youtu.be/nS3UaR7T1zU

### Repro steps

1. Find an entity behind a wall
2. Turn on kill aura
3. turn away from it

### Raven XD version

2.6 and 2.7

**Comment by xia-mc** [comment]
raycast: strict

**Comment by celakk1** [comment]
even with raycast strict it happens.
ive tested every raycast option

**Comment by xia-mc** [comment]
uhhhh
now you can use legit attack mode to slove this

I will fix it later

**Comment by celakk1** [comment]
its the same on legit attack mode

**Comment by celakk1** [comment]
seems to be fixed as of 2.10
