### ISSUE TITLE
intave velocity improvement

### ISSUE THREAD

**Issue by larryngton2** [xia-mc/Raven-XD#826]
### Pre-suggestion checklist

- [X] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [X] This feature doesn't already exist in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Other (please explain in description)

### Description

you could add a hurttime slider to the intave velocity which allows it to reduce only when the player's hurttime is equal to it, you can take inspiration from https://github.com/CCBlueX/LiquidBounce/blob/nextgen/src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/combat/velocity/mode/VelocityIntave.kt

**Comment by xia-mc** [comment]
it's patched rn

**Comment by larryngton2** [comment]
> it's patched rn

nope ive used this on liquidbounce for around a week
