### ISSUE TITLE
scaffold hypixel sprint mode not working diagonal

### ISSUE THREAD

**Issue by elpolake** [xia-mc/Raven-XD#830]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

hello i tried using scaffold hypixel sprint mode and it works while going straight and actually slows down but if going diagonally it still sprints but doesnt slow down

### Repro steps

1turn on the scaffold 2 go diagonal 3 get flagged 4 get banned

### Raven XD version

latest dev

**Comment by xia-mc** [comment]
known, it's patched rn
