### ISSUE TITLE
Bugged AntiCheat

### ISSUE THREAD

**Issue by xXGuiXxYT** [xia-mc/Raven-XD#84]
There is a bug in the "AntiCheat" function.  This bug consists of warning that Bedwars NPCs, for example, are using fly. Or even say that a player who hits another player 3.0 blocks away is AutoBlock. In short, I want to say that AntiCheat has a lot of bugs. I recommend tinkering with or developing an AntiCheat based on Tenacity's HackerDetector. Thanks!!!

**Comment by baka-iqboost** [comment]
Toggling Antibot might fix that
