### ISSUE TITLE
CustomFOV (Fixed Field Of VIew)

### ISSUE THREAD

**Issue by Kefpull** [xia-mc/Raven-XD#846]
### Pre-suggestion checklist

- [X] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [X] This feature doesn't already exist in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Adding a new hack.

### Description

Fixed FOV option that does not change with things that change fov like speed effects and sprinting. It is like NoHurtCam because it makes it easier to see in battle. This feature is in later versions of vanilla Minecraft, and in most hack clients. Looking at liquidbounce and other no fov mods it seems to not be overwhelmingly complicated, but I don't know how to do it myself

**Comment by xia-mc** [comment]
Use labymod 3
