### ISSUE TITLE
cant disable sprint scaffold

### ISSUE THREAD

**Issue by elpolake** [xia-mc/Raven-XD#847]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

pls make so we can disable the sprint in scaffold again

### Repro steps

use sprint scaffold disabled and doesnt work

### Raven XD version

latest

**Comment by Kefpull** [comment]
same here

**Comment by celakk1** [comment]
same, it feels like its just doing omnisprint and flags easily, cancel sprint doesnt really do anything either if set sprint to vanilla and checked "cancel sprint"

**Comment by Coccocoahelper** [comment]
> same, it feels like its just doing omnisprint and flags easily, cancel sprint doesnt really do anything either if set sprint to vanilla and checked "cancel sprint"

Pretty sure that just cancels the sprint packets. Haven't taken a look at the code yet, though.

**Comment by xia-mc** [comment]
'Cancel sprint' just cancel sprint packet, which can bypass some anticheats.
To disable sprint, you need change the sprint mode to 'Disabled'
