### ISSUE TITLE
noslow issue in feather client

### ISSUE THREAD

**Issue by PheKe** [xia-mc/Raven-XD#855]
### Pre-reporting checklist

- [ ] I have searched existing issues and didn't find any previous reports of this bug.
- [x] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [x] I have tried removing all other mods and the bug still happens.

### Description

i dont know how to explain it but here is the video
https://streamable.com/6r1d2h

### Repro steps

.

### Raven XD version

latest

**Comment by TejasLamba2006** [comment]
We don't support feather client. Switch to something else!
