### ISSUE TITLE
Update Discord Webhook URL Secret

### ISSUE THREAD

**Issue by Kefpull** [xia-mc/Raven-XD#858]
### Pre-suggestion checklist

- [X] I have searched existing issues and didn't find any previous issues with the same suggestion.
- [X] This is only one suggestion. I understand that GitHub issues don't work well with lists.
- [X] This feature doesn't already exist in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have looked at the code and am reasonably confident that this suggestion is possible to implement.

### What type of improvement are you suggesting?

Other (please explain in description)

### Description

[Java CI with Gradle](https://github.com/xia-mc/Raven-XD/actions/workflows/gradle.yml) always fails because there is no url specified for the discord webhook. Entering a valid url into secrets.DISCORD_WEBHOOK_URL would fix this.
![Pull requests · xia-mc_Raven-XD and 6 more pages - Personal - Microsoft​ Edge 12_2_2024 2_49_11 PM](https://github.com/user-attachments/assets/f1bcb858-a133-465e-b10e-6a5746bf7536)

**Comment by xia-mc** [comment]
Yes, pull-request build shouldn't be push to discord. Fixed in 31e731e and 1704c90. Now the build jar will be upload to github.
