### ISSUE TITLE
Alt+Tab Banned

### ISSUE THREAD

**Issue by Netbull0** [xia-mc/Raven-XD#859]
### Pre-reporting checklist

- [x] I have searched existing issues and didn't find any previous reports of this bug.
- [x] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [x] I have tried removing all other mods and the bug still happens.

### Description

In jartexnetwork when i alt+tab to other window i just saw i got auto banned by consol multiple times. When i played and used cheats, pvp etc its no problem. I dont know what happening when i open other window like google etc.

### Repro steps

1. Joined to Jartexnetwork
2. Alt+Tab
3. Console ban

### Raven XD version

9.19

**Comment by xia-mc** [comment]
Polar switch-window detection 👍

**Comment by Netbull0** [comment]
Where can i active it. Please help me
