### ISSUE TITLE
NoSlow Bug

### ISSUE THREAD

**Issue by wtfMikeyyy** [xia-mc/Raven-XD#868]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Raven XD. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

The NoSlow is always enabled, until turn on NoSlow and uncheck all the points.

### Repro steps

1. Start Game
2. Use Bow While walking
3. It will trigger NoSlow while its still disabled.

### Raven XD version

Latest

### Crash report (if applicable)

```plaintext
It Doesn't Crash
```

**Comment by xia-mc** [comment]
no, it works for me
