### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by kingdempa** [xia-mc/Raven-XD#88]
After i install raven 1.14 or raven 1.13 and i config it a bit i crash usually after either leaving the game or leaving a server with the error java.lang.NullPointerException. After the first crash i will crash on launch and sometimes the minecraft launcher wont fully close so i have to use the task manager to close it.

**Comment by kingdempa** [comment]
im not sure if its an issue for other versions

**Comment by KgDW** [comment]
try to del default config

**Comment by kingdempa** [comment]
> try to del default config

i did i reinstalled it and deleted the keystrokes folder three times it didint solve the issue

**Comment by kingdempa** [comment]
bro._.ski._53496 found the issue its caused by the ambience modules

**Comment by kingdempa** [comment]
bro._.ski._53496 found the issue its caused by the ambience modules

**Comment by KgDW** [comment]
need to fix☠️
